spring.application.name=ecommerce

resilience4j.ratelimiter.instances.checkout.limitForPeriod=5
resilience4j.ratelimiter.instances.checkout.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.checkout.timeoutDuration=0s
